#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  scripts/commit_push.sh [options] [commit message]

Options:
  -n, --dry-run  Run lint/test/stage only; do not commit or push
  -h, --help     Show this help message

Behavior:
  - If a commit message is provided, commits with -m.
  - If no message is provided, uses an autogenerated timestamp message.

What it does:
  1) uv run pre-commit run --all-files
  2) uv run pytest -q
  3) git add -A
  4) git commit -m "..."
  5) git push
EOF
}

dry_run=false
msg=""

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    -h|--help)
      usage
      exit 0
      ;;
    -n|--dry-run)
      dry_run=true
      ;;
    *)
      if [[ -z "$msg" ]]; then
        msg="$1"
      else
        msg="$msg $1"
      fi
      ;;
  esac
  shift
done

# Ensure we are at repository root regardless of caller location.
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/.." && pwd)"
cd "$repo_root"

uv run pre-commit run --all-files
uv run pytest -q
git add -A

if [[ "$dry_run" == true ]]; then
  echo "Dry run complete: lint/test/stage succeeded; skipping commit/push."
  exit 0
fi

if [[ -n "$msg" ]]; then
  git commit -m "$msg"
else
  auto_msg="chore: checkpoint $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "No commit message provided. Using: $auto_msg"
  git commit -m "$auto_msg"
fi

git push

echo "Done: committed and pushed."